"""In-shader correctness harness for the Lambert directional chart (V1).

Change ``directional-flow-parameterization`` swaps ``neural_flow.slang``'s
square<->direction map from the cylindrical equal-area chart (V0) to the Lambert
azimuthal equal-area chart (V1: Shirley concentric square->disk + the lift
``cosθ = 1 − r²``). These tests run the *real Slang chart* on the GPU and assert
the two properties the swap rests on:

  * **Round-trip identity** — ``square→dir→square`` and ``dir→square→dir`` recover
    the input (the chart is a bijection away from the pole/boundary degeneracies).
  * **Solid-angle normalization** — the chart's true area scaling ``|∂ω/∂z|``
    equals the coded constant Jacobian ``2π`` everywhere, so the flow's
    solid-angle density integrates to one (mirrors ``spline_flow/test_charts.py``
    §3.1, computed here as the numerical area element of the forward map).

Run (headless GPU env, see CLAUDE.md "Headless / offscreen rendering")::

    PYTHONPATH=src ./bin/python3.13 -m pytest tests/test_neural_chart.py -q
"""

from __future__ import annotations

import math

import numpy as np
import pytest

pytestmark = pytest.mark.gpu

TWO_PI = 2.0 * math.pi


def _grid(n, lo, hi):
    """n×n interior grid of (u, v) points in [lo, hi]²."""
    xs = np.linspace(lo, hi, n)
    return [(float(u), float(v)) for u in xs for v in xs]


def _v3(r):
    return np.array([float(r[0]), float(r[1]), float(r[2])], np.float64)


def _v2(r):
    return np.array([float(r[0]), float(r[1])], np.float64)


# ---------------------------------------------------------------------------
# Round-trip identity (the chart is a measure-preserving bijection)
# ---------------------------------------------------------------------------

def test_square_dir_square_roundtrip(neural_flow_harness):
    """square→dir→square recovers the input away from the disk centre.

    The chart centre (u=v=0.5) is the single pole where azimuth is undefined, so
    a small neighbourhood around it is excluded — every other interior point must
    round-trip to tolerance."""
    h = neural_flow_harness
    max_err = 0.0
    for u, v in _grid(21, 0.04, 0.96):
        if abs(u - 0.5) < 0.04 and abs(v - 0.5) < 0.04:
            continue  # skip the pole neighbourhood (azimuth singular)
        w = h.test_v1_square_to_dir([u, v])
        z2 = _v2(h.test_v1_dir_to_square([float(w[0]), float(w[1]), float(w[2])]))
        max_err = max(max_err, float(np.abs(z2 - np.array([u, v])).max()))
    assert max_err < 1e-4, f"square→dir→square max err {max_err:.2e}"


def test_dir_square_dir_roundtrip(neural_flow_harness):
    """dir→square→dir recovers the direction. Directions are generated by the
    forward chart over an interior grid, so they are always valid upper-hemisphere
    unit vectors."""
    h = neural_flow_harness
    max_err = 0.0
    for u, v in _grid(21, 0.04, 0.96):
        if abs(u - 0.5) < 0.04 and abs(v - 0.5) < 0.04:
            continue  # pole: forward maps it to the normal, inverse azimuth is undefined
        w0 = _v3(h.test_v1_square_to_dir([u, v]))
        z = h.test_v1_dir_to_square([float(w0[0]), float(w0[1]), float(w0[2])])
        w1 = _v3(h.test_v1_square_to_dir([float(z[0]), float(z[1])]))
        max_err = max(max_err, float(np.abs(w1 - w0).max()))
    assert max_err < 1e-4, f"dir→square→dir max err {max_err:.2e}"


def test_forward_returns_unit_upper_hemisphere(neural_flow_harness):
    """Every forward sample is a finite unit vector in the upper hemisphere
    (wi.y ≥ 0) — the chart is hemisphere-only and seam-free."""
    h = neural_flow_harness
    for u, v in _grid(17, 0.0, 1.0):
        w = _v3(h.test_v1_square_to_dir([u, v]))
        assert np.all(np.isfinite(w)), f"non-finite dir at ({u},{v}): {w}"
        assert abs(np.linalg.norm(w) - 1.0) < 1e-4, f"non-unit dir {w}"
        assert w[1] >= -1e-5, f"dir below hemisphere {w}"


# ---------------------------------------------------------------------------
# Solid-angle normalization (true area scaling == coded constant Jacobian 2π)
# ---------------------------------------------------------------------------

def _area_scaling_central(h, u, v, eps):
    """Numerical |∂ω/∂z| at (u, v) via central differences: area of the spherical
    parallelogram spanned by the forward map's partials. For an equal-area chart
    this is the constant 2π."""
    wup = _v3(h.test_v1_square_to_dir([u + eps, v]))
    wun = _v3(h.test_v1_square_to_dir([u - eps, v]))
    wvp = _v3(h.test_v1_square_to_dir([u, v + eps]))
    wvn = _v3(h.test_v1_square_to_dir([u, v - eps]))
    du = (wup - wun) / (2.0 * eps)
    dv = (wvp - wvn) / (2.0 * eps)
    return float(np.linalg.norm(np.cross(du, dv)))


def _on_wedge_seam(u, v, band):
    """True near a Shirley-concentric wedge boundary (|a| == |b|, i.e. the square's
    two diagonals) where the map is only C0 — a finite-difference stencil straddling
    the seam reports a spurious area scaling though the analytic value is still 2π."""
    return abs(abs(u - 0.5) - abs(v - 0.5)) < band


def test_area_scaling_is_constant_2pi(neural_flow_harness):
    """The chart's pointwise area scaling equals 2π everywhere (equal-area), so the
    coded constant Jacobian NF_LOG2PI is exact. The pole neighbourhood and the
    concentric wedge seams are excluded — the FD stencil is invalid across those
    C0 kinks; the integral test below still covers the full square (seams included)."""
    h = neural_flow_harness
    eps = 1e-3
    devs = []
    for u, v in _grid(25, 0.02, 0.98):
        if abs(u - 0.5) < 0.06 and abs(v - 0.5) < 0.06:
            continue
        if _on_wedge_seam(u, v, 2.0 * eps):
            continue
        devs.append(abs(_area_scaling_central(h, u, v, eps) - TWO_PI) / TWO_PI)
    devs = np.array(devs)
    # Central-difference error is O(eps²); equal-area makes the analytic value 2π.
    assert float(devs.mean()) < 1e-3, f"mean |Δ|/2π = {devs.mean():.2e}"
    assert float(devs.max()) < 1e-2, f"max |Δ|/2π = {devs.max():.2e}"


def test_solid_angle_integrates_to_2pi(neural_flow_harness):
    """Riemann sum of the area element over the unit square equals the hemisphere
    solid angle 2π — i.e. ∫ q_ω dω = 1 for the uniform base density q_□ = 1.
    Mirrors spline_flow/test_charts.py §3.1."""
    h = neural_flow_harness
    n = 64
    eps = 1.0 / (8 * n)
    cell = 1.0 / (n * n)
    total = 0.0
    for i in range(n):
        u = (i + 0.5) / n
        for j in range(n):
            v = (j + 0.5) / n
            total += _area_scaling_central(h, u, v, eps) * cell
    assert abs(total - TWO_PI) / TWO_PI < 1e-2, (
        f"∫|∂ω/∂z| dz = {total:.5f} (want 2π = {TWO_PI:.5f})"
    )
