"""Binding coverage for real passes — change ``recording-adapter-live-bindings``.

``Recorder.missing_bindings()`` names every shader global a dispatch left
unbound. On Metal an unbound global is a silent zero rather than a crash, so
catching one before the GPU is worth a lot — but only if both sides of the
comparison are real. Until this change every caller wrote both::

    pipe.reflect_globals({"outputBuffer", "sceneBuffer"})   # hand-written
    pipe.dispatch(8, 8, binds={"outputBuffer": buf})        # hand-written

which asserts that two literals the same author wrote disagree where that
author expected. Those scenarios still live in ``tests/test_gpu_backend.py``,
relabelled: they test the RECORDER, not any pass.

Here the two sides are both real, and neither is written in this file:

* The **declared** side comes from the compiler. ``slangc``'s reflection of each
  pass is generated offline into
  ``tests/fixtures/recording_pass_globals.json`` by
  ``tests/fixtures/gen_recording_pass_globals.py`` and trusted here exactly as
  the checked-in ``.spv`` is trusted. A hand parser could not tell a file-scope
  resource global from a function parameter of resource type without full scope
  tracking, and codex pre-merge review kept finding valid Slang spellings it
  under-reported — the exact fail-open the gate exists to prevent. The compiler
  does not miss a declaration, so that failure class is gone.
* The **bound** side comes from ``SceneResourceSet.metal_binds`` — the single
  builder the renderer's ``_build_metal_binds`` delegates to.

The negative control proves the comparison can still fail.

Hostless: plain ``pytest`` runs it (the golden is read, not regenerated), and
:func:`test_the_gate_runs_with_no_gpu_package_importable` proves it needs
neither backend.
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from skinny import recording_compute as rec
from skinny.gpu_resources import DECLARATIONS

GOLDEN_PATH = (Path(__file__).parent / "fixtures"
               / "recording_pass_globals.json")
GOLDEN = json.loads(GOLDEN_PATH.read_text())

PASSES = rec.RECORDABLE_PASSES
IDS = [p.name for p in PASSES]


def _default_layout(decl) -> bool:
    """Is this declaration in the plain RGB, no-denoiser layout the megakernel
    reflects? Uses `ResourceDecl.in_default_layout` where it exists (a base that
    carries the denoise/aov axes) and falls back to `not spectral` otherwise, so
    the megakernel gate reads the same on this branch and on one with denoise."""
    return getattr(decl, "in_default_layout", not decl.spectral)


def declared_globals(pass_) -> set[str]:
    """The compiler-reflected globals for a pass, from the checked-in golden.

    Trusted, not re-derived: the golden is regenerated by
    ``gen_recording_pass_globals.py`` and diffed against reality by the
    gpu-marked freshness test below.
    """
    return set(GOLDEN[pass_.name]["globals"])


# ── the gate ─────────────────────────────────────────────────────────────


def run_pass(pass_, declared=None) -> list[tuple[str, str]]:
    """Drive one registered pass through the recorder and report what it left
    unbound.

    The ONE call the coverage gate and its negative control both use: a
    parallel hand-built path would prove only that the parallel path works.
    ``declared`` overrides the golden set only for the negative control.
    """
    ctx = rec.RecordingContext()
    pipe = rec.ComputePipeline(ctx, rec.shader_dir(), pass_.entry_module,
                               pass_.entry_point)
    pipe.reflect_globals(declared_globals(pass_) if declared is None else declared)
    binds, bindless = pass_.binds(ctx)
    # `uniform_blob` binds `fc`, `bindless` binds the pool under its own global
    # — the same two non-`binds` channels the real dispatch uses.
    pipe.dispatch(8, 8, uniform_blob=b"", binds=binds, bindless=bindless)
    return ctx.recorder.missing_bindings()


@pytest.mark.parametrize("pass_", PASSES, ids=IDS)
def test_registered_pass_binds_every_declared_global(pass_):
    """Scenario: a fully bound pass reports nothing — every global the compiler
    reflects for the pass is supplied by the host's real bind map."""
    assert run_pass(pass_) == []


@pytest.mark.parametrize("pass_", PASSES, ids=IDS)
def test_declared_globals_come_from_the_compiler_not_the_test(pass_):
    """Scenario: globals come from the shader, not the test.

    The golden entry names the pass's own entry module/point, and its globals
    are non-empty — so no literal set written in this file is standing in for
    the compiler's reflection.
    """
    entry = GOLDEN[pass_.name]
    assert entry["entry_module"] == pass_.entry_module
    assert entry["entry_point"] == pass_.entry_point
    assert entry["globals"], f"{pass_.name} reflected nothing — golden is stale"


def test_the_golden_covers_exactly_the_registry():
    """The golden and the registry name the same passes — a pass added without
    regenerating the golden (or a stale golden entry) fails here rather than
    silently skipping coverage."""
    assert set(GOLDEN) == {p.name for p in PASSES}


def test_the_bind_map_is_the_hosts_own_builder():
    """The bound side is not written here either: it is whatever
    ``SceneResourceSet.metal_binds`` produces, which is the single builder the
    renderer's ``_build_metal_binds`` delegates to."""
    import inspect

    from skinny import gpu_resources

    binds, _ = rec.scene_binds(rec.RecordingContext())
    assert set(binds) >= {d.metal for d in DECLARATIONS
                          if d.metal and _default_layout(d)}
    body = inspect.getsource(gpu_resources.SceneResourceSet.metal_binds)
    assert "commonSampler" in body, (
        "the renderer-owned globals must be added inside metal_binds, or the "
        "gate sees a different map from the one a frame binds")


# ── the golden agrees with an independently maintained table (D5) ────────


def test_golden_agrees_with_the_gpu_resource_inventory():
    """Scenario: the compiler reflection agrees with an independently maintained
    table.

    ``gpu_resources.DECLARATIONS`` records each resource's Vulkan binding number
    and Metal global name for a completely different reason (allocating and
    binding them). The megakernel golden must name exactly the default-layout
    inventory resources it reaches — a fourth going missing, or an inventory
    name the golden lacks, fails here.
    """
    megakernel = declared_globals(next(p for p in PASSES if p.name == "megakernel"))
    inventory = {d.metal for d in DECLARATIONS if _default_layout(d) and d.metal}
    # The megakernel strips the neural proposal at build, so the three neural
    # buffers are the only default-layout inventory resources it does not
    # declare (Compatibility matrix: neural is wavefront-only). That exclusion
    # is the independently maintained leg.
    MEGAKERNEL_ABSENT = {"neuralWeights", "neuralBiases", "neuralLayers"}
    # EQUALITY, not containment (codex review): the golden's inventory-named
    # subset must be EXACTLY `inventory − MEGAKERNEL_ABSENT`. Containment
    # accepted a golden that carried an extra inventory name it should not (e.g.
    # a stray `neuralWeights`) — the drift D5 exists to catch. Restrict to
    # inventory names first, because the golden also carries `fc` /
    # `flatMaterialTextures` / `commonSampler`, which the inventory does not name
    # (pinned separately below).
    golden_inventory = megakernel & inventory
    assert golden_inventory == inventory - MEGAKERNEL_ABSENT, (
        "megakernel golden disagrees with the resource inventory: "
        f"missing {sorted((inventory - MEGAKERNEL_ABSENT) - golden_inventory)}, "
        f"unexpected {sorted(golden_inventory - (inventory - MEGAKERNEL_ABSENT))}"
        " — regenerate the golden or fix the inventory")
    # …and the absent set is genuinely absent, not merely un-required: a golden
    # that started declaring a neural buffer must fail, which pure equality above
    # would already catch, but this states the intent directly.
    assert not (megakernel & MEGAKERNEL_ABSENT), (
        f"golden declares a resource the megakernel strips at build: "
        f"{sorted(megakernel & MEGAKERNEL_ABSENT)}")


def test_the_globals_without_an_inventory_entry_are_the_recorded_three():
    """The three megakernel globals ``DECLARATIONS`` deliberately does not name:
    the uniform block (bound as a blob, not a resource), the bindless pool
    (passed as the separate ``bindless`` argument) and the renderer-owned shared
    sampler. Pinned so a fourth cannot appear unnoticed."""
    megakernel = declared_globals(next(p for p in PASSES if p.name == "megakernel"))
    named = {d.metal for d in DECLARATIONS if d.metal}
    samplers = {d.metal + "Sampler" for d in DECLARATIONS if d.metal_sampler}
    unnamed = megakernel - named - samplers
    assert unnamed == {"fc", "flatMaterialTextures", "commonSampler"}


# ── the golden is fresh (regeneration matches, gpu-marked) ───────────────


@pytest.mark.gpu
def test_golden_matches_a_fresh_reflection():
    """The checked-in golden equals what ``slangc`` reflects today. Marked
    ``gpu`` because it shells out to the compiler; the hostless gate above
    trusts the golden exactly as the pinned ``.spv`` is trusted, and this is the
    freshness check that keeps that trust honest (run it after any shader edit
    that touches a registered pass's globals)."""
    from tests.fixtures import gen_recording_pass_globals as gen

    fresh = gen.build()
    assert fresh == GOLDEN, (
        "the recording-pass globals golden is stale — regenerate it with "
        "`python -m tests.fixtures.gen_recording_pass_globals`")


# ── the registry is complete (D3) ────────────────────────────────────────


def test_every_compute_entry_is_registered_or_excluded():
    """Scenario: a new pass without registration fails the build."""
    registered = {p.entry_key for p in PASSES}
    excluded = {x.key for x in rec.RECORDABLE_EXCLUSIONS}
    missing = sorted(rec.compute_entry_points() - registered - excluded)
    assert missing == [], (
        "these compute entry points are neither registered in "
        "RECORDABLE_PASSES nor excluded with a reason in "
        f"RECORDABLE_EXCLUSIONS: {missing}")


def test_no_exclusion_names_a_pass_that_no_longer_exists():
    """Scenario: an exclusion states its reason — and none is stale.

    A stale exclusion silently re-admits the gap it was meant to bound.
    """
    stale = sorted({x.key for x in rec.RECORDABLE_EXCLUSIONS}
                   - rec.compute_entry_points())
    assert stale == []
    for exclusion in rec.RECORDABLE_EXCLUSIONS:
        assert len(exclusion.reason) > 20, exclusion


def test_no_entry_point_is_both_registered_and_excluded():
    registered = {p.entry_key for p in PASSES}
    both = registered & {x.key for x in rec.RECORDABLE_EXCLUSIONS}
    assert both == set()


def test_entry_points_are_keyed_by_module_as_well_as_name():
    """Multiple modules declare `computeMain` (foundation_trivial, tool_probe,
    and the denoise passes when present); a name-keyed map would collapse them
    and report an unregistered pass as covered. Keying by (module, name) keeps
    each distinct."""
    same_name = [key for key in rec.compute_entry_points()
                 if key[1] == "computeMain"]
    assert len(same_name) >= 2


def test_an_entry_point_with_a_brace_in_a_comment_is_still_found(tmp_path):
    """`compute_entry_points` strips comments over the whole file, so a `{`
    inside a `//` comment between `[shader("compute")]` and `void` must not hide
    the entry from the scan (codex review)."""
    (tmp_path / "m.slang").write_text(
        '[shader("compute")] // writes into {tile}\n'
        "[numthreads(1,1,1)]\n"
        "void kern(uint3 t : SV_DispatchThreadID) {}\n")
    assert ("m", "kern") in rec.compute_entry_points(tmp_path)


def test_entry_scan_excludes_generated_untracked_shaders(tmp_path):
    """The scan counts only SOURCE (git-tracked) shaders, not the renderer's
    per-scene generated output.

    The renderer emits `generated_materials.slang` and per-material
    `wavefront/shade_<Material>.slang` modules — each with a `[shader("compute")]`
    entry — into the tree at run time. They are never `git add`ed, so on any
    checkout that has rendered, a plain rglob would surface them and fail the
    registry meta-test with entries that must not be registered. A git fixture
    proves the tracked source entry is found and the untracked generated one is
    not."""
    import subprocess

    def git(*args):
        subprocess.run(["git", "-C", str(tmp_path), *args],
                       check=True, capture_output=True)

    git("init", "-q")
    (tmp_path / "wavefront").mkdir()
    (tmp_path / "src_pass.slang").write_text(
        '[shader("compute")] [numthreads(1,1,1)]\n'
        "void sourceKern(uint3 t : SV_DispatchThreadID) {}\n")
    git("add", "src_pass.slang")
    # Emitted at run time, never committed — a real compute entry.
    (tmp_path / "wavefront" / "shade_Marble.slang").write_text(
        '[shader("compute")] [numthreads(1,1,1)]\n'
        "void shadeSurface_Marble(uint3 t : SV_DispatchThreadID) {}\n")

    found = rec.compute_entry_points(tmp_path)
    assert ("src_pass", "sourceKern") in found
    assert ("wavefront.shade_Marble", "shadeSurface_Marble") not in found


def test_entry_scan_survives_block_comments_and_whitespace(tmp_path):
    """Codex review, finding 4: the entry scan strips BOTH comment forms and
    tolerates Slang's whitespace, so it neither misses a real entry nor invents
    a phantom one.

    Three cases, all valid Slang: a `{` inside a `/* */` block comment between
    the attribute and `void` (was hidden); `shader ("compute")` with spaces (was
    missed); and an entry-shaped string sitting inside a block comment (was
    reported as real).
    """
    (tmp_path / "block.slang").write_text(
        '[shader("compute")] /* fills { the tile */\n'
        "[numthreads(1,1,1)]\n"
        "void blockKern(uint3 t : SV_DispatchThreadID) {}\n")
    (tmp_path / "space.slang").write_text(
        '[ shader ( "compute" ) ]\n'
        "[numthreads(1,1,1)]\n"
        "void spaceKern(uint3 t : SV_DispatchThreadID) {}\n")
    (tmp_path / "fake.slang").write_text(
        "/* not real:\n"
        '   [shader("compute")] void ghost(uint3 t : SV_DispatchThreadID) {}\n'
        "*/\n"
        "float helper() { return 1.0; }\n")
    found = rec.compute_entry_points(tmp_path)
    assert ("block", "blockKern") in found
    assert ("space", "spaceKern") in found
    assert ("fake", "ghost") not in found


def test_entry_scan_does_not_join_two_line_comments_into_a_block(tmp_path):
    """Codex round-5 regression: stripping block comments before line comments
    let a `/*` in one `//` line and a `*/` in a later `//` line be read as a
    real block delimiter, erasing the entry between them. The single-pass lexer
    knows `/*` inside a `//` line is just text, so the entry survives."""
    (tmp_path / "m.slang").write_text(
        "// opens a fake block /*\n"
        '[shader("compute")]\n'
        "[numthreads(1,1,1)]\n"
        "void survivor(uint3 t : SV_DispatchThreadID) {}\n"
        "// closes it */\n")
    assert ("m", "survivor") in rec.compute_entry_points(tmp_path)


def test_entry_scan_treats_an_inline_block_comment_as_a_separator(tmp_path):
    """Codex round-6: a removed block comment must become a space, not nothing —
    an inline `/* */` is a legal token separator, so `void/* */name` lexes to
    `void name`. Deleting it outright yields `voidname` and the entry vanishes
    before `_ENTRY_RE`."""
    (tmp_path / "m.slang").write_text(
        '[shader("compute")] [numthreads(1,1,1)]\n'
        "void/* legal separator */sep(uint3 t : SV_DispatchThreadID) {}\n")
    assert ("m", "sep") in rec.compute_entry_points(tmp_path)


def test_entry_module_key_is_platform_neutral(tmp_path):
    """Codex round-6: the module key is `".".join(parts)`, not
    `.replace("/", ".")`, so a nested entry keys the same on every OS and matches
    its dotted registry/exclusion entry."""
    nested = tmp_path / "wavefront"
    nested.mkdir()
    (nested / "wavefront_path.slang").write_text(
        '[shader("compute")] [numthreads(1,1,1)]\n'
        "void wfKern(uint3 t : SV_DispatchThreadID) {}\n")
    assert ("wavefront.wavefront_path", "wfKern") in rec.compute_entry_points(
        tmp_path)


# ── the gate is provably able to fail (D4) ───────────────────────────────


def test_the_negative_control_reports_the_omitted_global():
    """Scenario: the negative control is reported.

    A fixture pass identical to the megakernel except that its bind map drops
    exactly one global the compiler reflects. Routed through :func:`run_pass` —
    the same call the real gate uses.
    """
    omitted = "sphereLights"
    megakernel = next(p for p in PASSES if p.name == "megakernel")

    def sabotaged(ctx):
        binds, bindless = megakernel.binds(ctx)
        assert omitted in binds, "the fixture must omit a genuinely bound name"
        return ({k: v for k, v in binds.items() if k != omitted}, bindless)

    control = rec.RecordablePass(
        name="megakernel", entry_module=megakernel.entry_module,
        entry_point=megakernel.entry_point, key=megakernel.key,
        binds=sabotaged,
    )
    assert run_pass(control) == [(megakernel.entry_point, omitted)]
    # The real pass, through the same call, still reports nothing — so the
    # control isolates the omission rather than a broken harness.
    assert run_pass(megakernel) == []


def test_a_present_but_empty_binding_still_counts_as_omitted():
    """A key bound to `None` is unbound, not bound (the rule
    `tests/test_gpu_backend.py::test_recorder_treats_a_none_resource_as_unbound`
    pins). Asserted here too, because it is what stops a skipped bind from
    reading as a satisfied one for a real pass."""
    omitted = "sphereLights"
    megakernel = next(p for p in PASSES if p.name == "megakernel")

    def nulled(ctx):
        binds, bindless = megakernel.binds(ctx)
        return ({**binds, omitted: None}, bindless)

    control = rec.RecordablePass(
        name="megakernel", entry_module=megakernel.entry_module,
        entry_point=megakernel.entry_point, key=megakernel.key, binds=nulled,
    )
    assert run_pass(control) == [(megakernel.entry_point, omitted)]


# ── hostless (task 6.2) ──────────────────────────────────────────────────

GPU_PACKAGES = ("vulkan", "slangpy")

_BLOCKER = """
import sys

class _Blocked:
    def find_module(self, name, path=None):
        return self.find_spec(name, path)

    def find_spec(self, name, path=None, target=None):
        if name.split(".")[0] in {gpu!r}:
            raise ImportError("blocked by the hostless coverage gate: " + name)
        return None

sys.meta_path.insert(0, _Blocked())
"""


def test_the_gate_runs_with_no_gpu_package_importable():
    """Scenario: coverage runs with no GPU.

    The whole point of a recording adapter is that binding coverage stops
    needing a dual-device host, so the gate is proved to complete in a process
    where neither backend package can even be imported. The golden is read from
    disk, so no compiler runs here either.
    """
    code = _BLOCKER.format(gpu=set(GPU_PACKAGES)) + textwrap.dedent(f"""
        import json, sys
        from pathlib import Path

        from skinny import recording_compute as rec

        golden = json.loads(Path({str(GOLDEN_PATH)!r}).read_text())
        for p in rec.RECORDABLE_PASSES:
            ctx = rec.RecordingContext()
            pipe = rec.ComputePipeline(ctx, rec.shader_dir(), p.entry_module,
                                       p.entry_point)
            pipe.reflect_globals(golden[p.name]["globals"])
            binds, bindless = p.binds(ctx)
            pipe.dispatch(8, 8, uniform_blob=b"", binds=binds,
                          bindless=bindless)
            missing = ctx.recorder.missing_bindings()
            assert missing == [], (p.name, missing)
        for gpu in ("vulkan", "slangpy"):
            assert gpu not in sys.modules, gpu
        print("OK", len(rec.RECORDABLE_PASSES))
    """)
    result = subprocess.run([sys.executable, "-c", code],
                            capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stderr
    assert result.stdout.startswith("OK "), result.stdout
